export const COUNTRIES = [
  { value: "Afghanistan", label: "\u{1F1E6}\u{1F1EB} Afghanistan" },
  { value: "Albania", label: "\u{1F1E6}\u{1F1F1} Albania" },
  { value: "Algeria", label: "\u{1F1E9}\u{1F1FF} Algeria" },
  { value: "Andorra", label: "\u{1F1E6}\u{1F1E9} Andorra" },
  { value: "Angola", label: "\u{1F1E6}\u{1F1F4} Angola" },
  {
    value: "Antigua and Barbuda",
    label: "\u{1F1E6}\u{1F1EC} Antigua and Barbuda",
  },
  { value: "Argentina", label: "\u{1F1E6}\u{1F1F7} Argentina" },
  { value: "Armenia", label: "\u{1F1E6}\u{1F1F2} Armenia" },
  { value: "Australia", label: "\u{1F1E6}\u{1F1FA} Australia" },
  { value: "Austria", label: "\u{1F1E6}\u{1F1F9} Austria" },
  { value: "Azerbaijan", label: "\u{1F1E6}\u{1F1FF} Azerbaijan" },
  { value: "Bahamas", label: "\u{1F1E7}\u{1F1F8} Bahamas" },
  { value: "Bahrain", label: "\u{1F1E7}\u{1F1ED} Bahrain" },
  { value: "Bangladesh", label: "\u{1F1E7}\u{1F1E9} Bangladesh" },
  { value: "Barbados", label: "\u{1F1E7}\u{1F1E7} Barbados" },
  { value: "Belarus", label: "\u{1F1E7}\u{1F1FE} Belarus" },
  { value: "Belgium", label: "\u{1F1E7}\u{1F1EA} Belgium" },
  { value: "Belize", label: "\u{1F1E7}\u{1F1FF} Belize" },
  { value: "Benin", label: "\u{1F1E7}\u{1F1EF} Benin" },
  { value: "Bhutan", label: "\u{1F1E7}\u{1F1F9} Bhutan" },
  { value: "Bolivia", label: "\u{1F1E7}\u{1F1F4} Bolivia" },
  {
    value: "Bosnia and Herzegovina",
    label: "\u{1F1E7}\u{1F1E6} Bosnia and Herzegovina",
  },
  { value: "Botswana", label: "\u{1F1E7}\u{1F1FC} Botswana" },
  { value: "Brazil", label: "\u{1F1E7}\u{1F1F7} Brazil" },
  { value: "Brunei", label: "\u{1F1E7}\u{1F1F3} Brunei" },
  { value: "Bulgaria", label: "\u{1F1E7}\u{1F1EC} Bulgaria" },
  { value: "Burkina Faso", label: "\u{1F1E7}\u{1F1EB} Burkina Faso" },
  { value: "Burundi", label: "\u{1F1E7}\u{1F1EE} Burundi" },
  { value: "Cabo Verde", label: "\u{1F1E8}\u{1F1FB} Cabo Verde" },
  { value: "Cambodia", label: "\u{1F1F0}\u{1F1ED} Cambodia" },
  { value: "Cameroon", label: "\u{1F1E8}\u{1F1F2} Cameroon" },
  { value: "Canada", label: "\u{1F1E8}\u{1F1E6} Canada" },
  {
    value: "Central African Republic",
    label: "\u{1F1E8}\u{1F1EB} Central African Republic",
  },
  { value: "Chad", label: "\u{1F1F9}\u{1F1E9} Chad" },
  { value: "Chile", label: "\u{1F1E8}\u{1F1F1} Chile" },
  { value: "China", label: "\u{1F1E8}\u{1F1F3} China" },
  { value: "Colombia", label: "\u{1F1E8}\u{1F1F4} Colombia" },
  { value: "Comoros", label: "\u{1F1F0}\u{1F1F2} Comoros" },
  { value: "Congo", label: "\u{1F1E8}\u{1F1EC} Congo" },
  { value: "Costa Rica", label: "\u{1F1E8}\u{1F1F7} Costa Rica" },
  { value: "Croatia", label: "\u{1F1ED}\u{1F1F7} Croatia" },
  { value: "Cuba", label: "\u{1F1E8}\u{1F1FA} Cuba" },
  { value: "Cyprus", label: "\u{1F1E8}\u{1F1FE} Cyprus" },
  { value: "Czech Republic", label: "\u{1F1E8}\u{1F1FF} Czech Republic" },
  {
    value: "Democratic Republic of the Congo",
    label: "\u{1F1E8}\u{1F1E9} Democratic Republic of the Congo",
  },
  { value: "Denmark", label: "\u{1F1E9}\u{1F1F0} Denmark" },
  { value: "Djibouti", label: "\u{1F1E9}\u{1F1EF} Djibouti" },
  { value: "Dominica", label: "\u{1F1E9}\u{1F1F2} Dominica" },
  {
    value: "Dominican Republic",
    label: "\u{1F1E9}\u{1F1F4} Dominican Republic",
  },
  { value: "East Timor", label: "\u{1F1F9}\u{1F1F1} East Timor" },
  { value: "Ecuador", label: "\u{1F1EA}\u{1F1E8} Ecuador" },
  { value: "Egypt", label: "\u{1F1EA}\u{1F1EC} Egypt" },
  { value: "El Salvador", label: "\u{1F1F8}\u{1F1FB} El Salvador" },
  { value: "Equatorial Guinea", label: "\u{1F1EC}\u{1F1F6} Equatorial Guinea" },
  { value: "Eritrea", label: "\u{1F1EA}\u{1F1F7} Eritrea" },
  { value: "Estonia", label: "\u{1F1EA}\u{1F1EA} Estonia" },
  { value: "Eswatini", label: "\u{1F1F8}\u{1F1FF} Eswatini" },
  { value: "Ethiopia", label: "\u{1F1EA}\u{1F1F9} Ethiopia" },
  { value: "Fiji", label: "\u{1F1EB}\u{1F1EF} Fiji" },
  { value: "Finland", label: "\u{1F1EB}\u{1F1EE} Finland" },
  { value: "France", label: "\u{1F1EB}\u{1F1F7} France" },
  { value: "Gabon", label: "\u{1F1EC}\u{1F1E6} Gabon" },
  { value: "Gambia", label: "\u{1F1EC}\u{1F1F2} Gambia" },
  { value: "Georgia", label: "\u{1F1EC}\u{1F1EA} Georgia" },
  { value: "Germany", label: "\u{1F1E9}\u{1F1EA} Germany" },
  { value: "Ghana", label: "\u{1F1EC}\u{1F1ED} Ghana" },
  { value: "Greece", label: "\u{1F1EC}\u{1F1F7} Greece" },
  { value: "Grenada", label: "\u{1F1EC}\u{1F1E9} Grenada" },
  { value: "Guatemala", label: "\u{1F1EC}\u{1F1F9} Guatemala" },
  { value: "Guinea", label: "\u{1F1EC}\u{1F1F3} Guinea" },
  { value: "Guinea-Bissau", label: "\u{1F1EC}\u{1F1FC} Guinea-Bissau" },
  { value: "Guyana", label: "\u{1F1EC}\u{1F1FE} Guyana" },
  { value: "Haiti", label: "\u{1F1ED}\u{1F1F9} Haiti" },
  { value: "Honduras", label: "\u{1F1ED}\u{1F1F3} Honduras" },
  { value: "Hungary", label: "\u{1F1ED}\u{1F1FA} Hungary" },
  { value: "Iceland", label: "\u{1F1EE}\u{1F1F8} Iceland" },
  { value: "India", label: "\u{1F1EE}\u{1F1F3} India" },
  { value: "Indonesia", label: "\u{1F1EE}\u{1F1E9} Indonesia" },
  { value: "Iran", label: "\u{1F1EE}\u{1F1F7} Iran" },
  { value: "Iraq", label: "\u{1F1EE}\u{1F1F6} Iraq" },
  { value: "Ireland", label: "\u{1F1EE}\u{1F1EA} Ireland" },
  { value: "Israel", label: "\u{1F1EE}\u{1F1F1} Israel" },
  { value: "Italy", label: "\u{1F1EE}\u{1F1F9} Italy" },
  { value: "Ivory Coast", label: "\u{1F1E8}\u{1F1EE} Ivory Coast" },
  { value: "Jamaica", label: "\u{1F1EF}\u{1F1F2} Jamaica" },
  { value: "Japan", label: "\u{1F1EF}\u{1F1F5} Japan" },
  { value: "Jordan", label: "\u{1F1EF}\u{1F1F4} Jordan" },
  { value: "Kazakhstan", label: "\u{1F1F0}\u{1F1FF} Kazakhstan" },
  { value: "Kenya", label: "\u{1F1F0}\u{1F1EA} Kenya" },
  { value: "Kiribati", label: "\u{1F1F0}\u{1F1EE} Kiribati" },
  { value: "Kosovo", label: "\u{1F1FD}\u{1F1F0} Kosovo" },
  { value: "Kuwait", label: "\u{1F1F0}\u{1F1FC} Kuwait" },
  { value: "Kyrgyzstan", label: "\u{1F1F0}\u{1F1EC} Kyrgyzstan" },
  { value: "Laos", label: "\u{1F1F1}\u{1F1E6} Laos" },
  { value: "Latvia", label: "\u{1F1F1}\u{1F1FB} Latvia" },
  { value: "Lebanon", label: "\u{1F1F1}\u{1F1E7} Lebanon" },
  { value: "Lesotho", label: "\u{1F1F1}\u{1F1F8} Lesotho" },
  { value: "Liberia", label: "\u{1F1F1}\u{1F1F7} Liberia" },
  { value: "Libya", label: "\u{1F1F1}\u{1F1FE} Libya" },
  { value: "Liechtenstein", label: "\u{1F1F1}\u{1F1EE} Liechtenstein" },
  { value: "Lithuania", label: "\u{1F1F1}\u{1F1F9} Lithuania" },
  { value: "Luxembourg", label: "\u{1F1F1}\u{1F1FA} Luxembourg" },
  { value: "Madagascar", label: "\u{1F1F2}\u{1F1EC} Madagascar" },
  { value: "Malawi", label: "\u{1F1F2}\u{1F1FC} Malawi" },
  { value: "Malaysia", label: "\u{1F1F2}\u{1F1FE} Malaysia" },
  { value: "Maldives", label: "\u{1F1F2}\u{1F1FB} Maldives" },
  { value: "Mali", label: "\u{1F1F2}\u{1F1F1} Mali" },
  { value: "Malta", label: "\u{1F1F2}\u{1F1F9} Malta" },
  { value: "Marshall Islands", label: "\u{1F1F2}\u{1F1ED} Marshall Islands" },
  { value: "Mauritania", label: "\u{1F1F2}\u{1F1F7} Mauritania" },
  { value: "Mauritius", label: "\u{1F1F2}\u{1F1FA} Mauritius" },
  { value: "Mexico", label: "\u{1F1F2}\u{1F1FD} Mexico" },
  { value: "Micronesia", label: "\u{1F1EB}\u{1F1F2} Micronesia" },
  { value: "Moldova", label: "\u{1F1F2}\u{1F1E9} Moldova" },
  { value: "Monaco", label: "\u{1F1F2}\u{1F1E8} Monaco" },
  { value: "Mongolia", label: "\u{1F1F2}\u{1F1F3} Mongolia" },
  { value: "Montenegro", label: "\u{1F1F2}\u{1F1EA} Montenegro" },
  { value: "Morocco", label: "\u{1F1F2}\u{1F1E6} Morocco" },
  { value: "Mozambique", label: "\u{1F1F2}\u{1F1FF} Mozambique" },
  { value: "Myanmar", label: "\u{1F1F2}\u{1F1F2} Myanmar" },
  { value: "Namibia", label: "\u{1F1F3}\u{1F1E6} Namibia" },
  { value: "Nauru", label: "\u{1F1F3}\u{1F1F7} Nauru" },
  { value: "Nepal", label: "\u{1F1F3}\u{1F1F5} Nepal" },
  { value: "Netherlands", label: "\u{1F1F3}\u{1F1F1} Netherlands" },
  { value: "New Zealand", label: "\u{1F1F3}\u{1F1FF} New Zealand" },
  { value: "Nicaragua", label: "\u{1F1F3}\u{1F1EE} Nicaragua" },
  { value: "Niger", label: "\u{1F1F3}\u{1F1EA} Niger" },
  { value: "Nigeria", label: "\u{1F1F3}\u{1F1EC} Nigeria" },
  { value: "North Korea", label: "\u{1F1F0}\u{1F1F5} North Korea" },
  { value: "North Macedonia", label: "\u{1F1F2}\u{1F1F0} North Macedonia" },
  { value: "Norway", label: "\u{1F1F3}\u{1F1F4} Norway" },
  { value: "Oman", label: "\u{1F1F4}\u{1F1F2} Oman" },
  { value: "Pakistan", label: "\u{1F1F5}\u{1F1F0} Pakistan" },
  { value: "Palau", label: "\u{1F1F5}\u{1F1FC} Palau" },
  { value: "Palestine", label: "\u{1F1F5}\u{1F1F8} Palestine" },
  { value: "Panama", label: "\u{1F1F5}\u{1F1E6} Panama" },
  { value: "Papua New Guinea", label: "\u{1F1F5}\u{1F1EC} Papua New Guinea" },
  { value: "Paraguay", label: "\u{1F1F5}\u{1F1FE} Paraguay" },
  { value: "Peru", label: "\u{1F1F5}\u{1F1EA} Peru" },
  { value: "Philippines", label: "\u{1F1F5}\u{1F1ED} Philippines" },
  { value: "Poland", label: "\u{1F1F5}\u{1F1F1} Poland" },
  { value: "Portugal", label: "\u{1F1F5}\u{1F1F9} Portugal" },
  { value: "Qatar", label: "\u{1F1F6}\u{1F1E6} Qatar" },
  { value: "Romania", label: "\u{1F1F7}\u{1F1F4} Romania" },
  { value: "Russia", label: "\u{1F1F7}\u{1F1FA} Russia" },
  { value: "Rwanda", label: "\u{1F1F7}\u{1F1FC} Rwanda" },
  {
    value: "Saint Kitts and Nevis",
    label: "\u{1F1F0}\u{1F1F3} Saint Kitts and Nevis",
  },
  { value: "Saint Lucia", label: "\u{1F1F1}\u{1F1E8} Saint Lucia" },
  {
    value: "Saint Vincent and the Grenadines",
    label: "\u{1F1FB}\u{1F1E8} Saint Vincent and the Grenadines",
  },
  { value: "Samoa", label: "\u{1F1FC}\u{1F1F8} Samoa" },
  { value: "San Marino", label: "\u{1F1F8}\u{1F1F2} San Marino" },
  {
    value: "Sao Tome and Principe",
    label: "\u{1F1F8}\u{1F1F9} Sao Tome and Principe",
  },
  { value: "Saudi Arabia", label: "\u{1F1F8}\u{1F1E6} Saudi Arabia" },
  { value: "Senegal", label: "\u{1F1F8}\u{1F1F3} Senegal" },
  { value: "Serbia", label: "\u{1F1F7}\u{1F1F8} Serbia" },
  { value: "Seychelles", label: "\u{1F1F8}\u{1F1E8} Seychelles" },
  { value: "Sierra Leone", label: "\u{1F1F8}\u{1F1F1} Sierra Leone" },
  { value: "Singapore", label: "\u{1F1F8}\u{1F1EC} Singapore" },
  { value: "Slovakia", label: "\u{1F1F8}\u{1F1F0} Slovakia" },
  { value: "Slovenia", label: "\u{1F1F8}\u{1F1EE} Slovenia" },
  { value: "Solomon Islands", label: "\u{1F1F8}\u{1F1E7} Solomon Islands" },
  { value: "Somalia", label: "\u{1F1F8}\u{1F1F4} Somalia" },
  { value: "South Africa", label: "\u{1F1FF}\u{1F1E6} South Africa" },
  { value: "South Korea", label: "\u{1F1F0}\u{1F1F7} South Korea" },
  { value: "South Sudan", label: "\u{1F1F8}\u{1F1F8} South Sudan" },
  { value: "Spain", label: "\u{1F1EA}\u{1F1F8} Spain" },
  { value: "Sri Lanka", label: "\u{1F1F1}\u{1F1F0} Sri Lanka" },
  { value: "Sudan", label: "\u{1F1F8}\u{1F1E9} Sudan" },
  { value: "Suriname", label: "\u{1F1F8}\u{1F1F7} Suriname" },
  { value: "Sweden", label: "\u{1F1F8}\u{1F1EA} Sweden" },
  { value: "Switzerland", label: "\u{1F1E8}\u{1F1ED} Switzerland" },
  { value: "Syria", label: "\u{1F1F8}\u{1F1FE} Syria" },
  { value: "Taiwan", label: "\u{1F1F9}\u{1F1FC} Taiwan" },
  { value: "Tajikistan", label: "\u{1F1F9}\u{1F1EF} Tajikistan" },
  { value: "Tanzania", label: "\u{1F1F9}\u{1F1FF} Tanzania" },
  { value: "Thailand", label: "\u{1F1F9}\u{1F1ED} Thailand" },
  { value: "Togo", label: "\u{1F1F9}\u{1F1EC} Togo" },
  { value: "Tonga", label: "\u{1F1F9}\u{1F1F4} Tonga" },
  {
    value: "Trinidad and Tobago",
    label: "\u{1F1F9}\u{1F1F9} Trinidad and Tobago",
  },
  { value: "Tunisia", label: "\u{1F1F9}\u{1F1F3} Tunisia" },
  { value: "Turkey", label: "\u{1F1F9}\u{1F1F7} Turkey" },
  { value: "Turkmenistan", label: "\u{1F1F9}\u{1F1F2} Turkmenistan" },
  { value: "Tuvalu", label: "\u{1F1F9}\u{1F1FB} Tuvalu" },
  { value: "Uganda", label: "\u{1F1FA}\u{1F1EC} Uganda" },
  { value: "Ukraine", label: "\u{1F1FA}\u{1F1E6} Ukraine" },
  {
    value: "United Arab Emirates",
    label: "\u{1F1E6}\u{1F1EA} United Arab Emirates",
  },
  { value: "United Kingdom", label: "\u{1F1EC}\u{1F1E7} United Kingdom" },
  { value: "United States", label: "\u{1F1FA}\u{1F1F8} United States" },
  { value: "Uruguay", label: "\u{1F1FA}\u{1F1FE} Uruguay" },
  { value: "Uzbekistan", label: "\u{1F1FA}\u{1F1FF} Uzbekistan" },
  { value: "Vanuatu", label: "\u{1F1FB}\u{1F1FA} Vanuatu" },
  { value: "Vatican City", label: "\u{1F1FB}\u{1F1E6} Vatican City" },
  { value: "Venezuela", label: "\u{1F1FB}\u{1F1EA} Venezuela" },
  { value: "Vietnam", label: "\u{1F1FB}\u{1F1F3} Vietnam" },
  { value: "Yemen", label: "\u{1F1FE}\u{1F1EA} Yemen" },
  { value: "Zambia", label: "\u{1F1FF}\u{1F1F2} Zambia" },
  { value: "Zimbabwe", label: "\u{1F1FF}\u{1F1FC} Zimbabwe" },
] as const;
